### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 98Kstar** [chibd2000/vue-myscan#2]
师傅好，ubuntu18，docker升级为最新版本，只修改了fofa地址，docker-composer为最新版本，报以下错：
Docker Compose version v2.15.1
root@vultr:~/vue-myscan# docker-compose up -d
[+] Running 0/0
 ⠋ celery Pulling                                                                                                                                                                                 0.1s
 ⠋ mysql Pulling                                                                                                                                                                                  0.1s
 ⠋ web Pulling                                                                                                                                                                                    0.1s
 ⠋ redis Pulling                                                                                                                                                                                  0.1s
error getting credentials - err: exit status 1, out: `GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files`
望解答，谢谢。

**Comment by chibd2000** [comment]
ubuntu18我没有搭建过，应该是docker的问题，我之前用的是ubuntu16是可以的 现在重新试了下centos7 也是没有什么问题的，如下所示 

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/47938748/212477507-ecbc067d-ac85-40c7-a20f-cec7abdaf058.png">

我帮你查询了下该问题，你尝试https://blog.csdn.net/RABCDXB/article/details/124829168 是否可以解决？

**Comment by 98Kstar** [comment]
谢谢师傅，已经解决，对没有google就提问的粗糙方式表示抱歉。
